In [ ]:
import pandas as pd

In [ ]:
# Reading a small set to check if we are not loading a data with empty columns (Unnamed columns)
airbnb_df=pd.read_csv(filepath_or_buffer='Airbnb_Open_Data.csv',dtype='str',nrows=4)

In [ ]:
airbnb_df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10,9,10/19/2021,0.21,4,6,286,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30,45,5/21/2022,0.38,4,2,228,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,...,$124,3,0,NaN,NaN,5,1,352,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30,270,7/5/2019,4.64,4,1,322,NaN,NaN

In [ ]:
# Review a record to get base idea of data
airbnb_df.head(1).T.to_dict()

{0: {'id': '1001254',
  'NAME': 'Clean & quiet apt home by the park',
  'host id': '80014485718',
  'host_identity_verified': 'unconfirmed',
  'host name': 'Madaline',
  'neighbourhood group': 'Brooklyn',
  'neighbourhood': 'Kensington',
  'lat': '40.64749',
  'long': '-73.97237',
  'country': 'United States',
  'country code': 'US',
  'instant_bookable': 'FALSE',
  'cancellation_policy': 'strict',
  'room type': 'Private room',
  'Construction year': '2020',
  'price': '$966 ',
  'service fee': '$193 ',
  'minimum nights': '10',
  'number of reviews': '9',
  'last review': '10/19/2021',
  'reviews per month': '0.21',
  'review rate number': '4',
  'calculated host listings count': '6',
  'availability 365': '286',
  'house_rules': "Clean up and treat the home the way you'd like your home to be treated.  No smoking.",
  'license': nan}}

In [ ]:
airbnb_df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [ ]:
airbnb_df=pd.read_csv(filepath_or_buffer='Airbnb_Open_Data.csv',dtype='str')

In [ ]:
airbnb_df.shape

(102599, 26)

In [ ]:
# Checking for missing values in the DataFrame
airbnb_df.isna().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [ ]:
# Printing unique values of each column for the first 50 rows
for c_name in airbnb_df.columns:
  print(f'{c_name} : {airbnb_df[c_name].head(50).unique()[0:10]}')

id : ['1001254' '1002102' '1002403' '1002755' '1003689' '1004098' '1004650'
 '1005202' '1005754' '1006307']
NAME : ['Clean & quiet apt home by the park' 'Skylit Midtown Castle'
 'THE VILLAGE OF HARLEM....NEW YORK !' nan
 'Entire Apt: Spacious Studio/Loft by central park'
 'Large Cozy 1 BR Apartment In Midtown East' 'BlissArtsSpace!'
 "Large Furnished Room Near B'way" 'Cozy Clean Guest Room - Family Apt'
 'Cute & Cozy Lower East Side 1 bdrm']
host id : ['80014485718' '52335172823' '78829239556' '85098326012' '92037596077'
 '45498551794' '61300605564' '90821839709' '79384379533' '75527839483']
host_identity_verified : ['unconfirmed' 'verified' nan]
host name : ['Madaline' 'Jenna' 'Elise' 'Garry' 'Lyndon' 'Michelle' 'Alberta' 'Emma'
 'Evelyn' 'Carl']
neighbourhood group : ['Brooklyn' 'Manhattan' 'brookln' 'manhatan' 'Queens']
neighbourhood : ['Kensington' 'Midtown' 'Harlem' 'Clinton Hill' 'East Harlem'
 'Murray Hill' 'Bedford-Stuyvesant' "Hell's Kitchen" 'Upper West Side'
 'Chinatown']
lat : ['40.64749' '40.75362' '40.80902' '40.68514' '40.79851' '40.74767'
 '40.68688' '40.76489' '40.80178' '40.71344']
long : ['-73.97237' '-73.98377' '-73.9419' '-73.95976' '-73.94399' '-73.975'
 '-73.95596' '-73.98493' '-73.96723' '-73.99037']
country : ['United States']
country code : ['US' nan]
instant_bookable : ['FALSE' 'TRUE' nan]
cancellation_policy : ['strict' 'moderate' 'flexible']
room type : ['Private room' 'Entire home/apt' 'Shared room']
Construction year : ['2020' '2007' '2005' '2009' '2013' '2015' '2004' '2008' '2010' '2019']
price : ['$966 ' '$142 ' '$620 ' '$368 ' '$204 ' '$577 ' '$71 ' '$1,060 '
 '$1,018 ' '$291 ']
service fee : ['$193 ' '$28 ' '$124 ' '$74 ' '$41 ' '$115 ' '$14 ' '$212 ' '$204 '
 '$58 ']
minimum nights : ['10' '30' '3' '45' '2' '1' '5' '4' '90' '7']
number of reviews : ['9' '45' '0' '270' '74' '49' '430' '118' '160' '53']
last review : ['10/19/2021' '5/21/2022' nan '7/5/2019' '11/19/2018' '6/22/2019'
 '10/5/2017' '6/24/2019' '7/21/2017' '6/9/2019']
reviews per month : ['0.21' '0.38' nan '4.64' '0.1' '0.59' '0.4' '3.47' '0.99' '1.33']
review rate number : ['4' '5' '3' nan '2' '1']
calculated host listings count : ['6' '2' '1' '4' '3']
availability 365 : ['286' '228' '352' '322' '289' '374' '224' '219' '180' '375']
house_rules : ["Clean up and treat the home the way you'd like your home to be treated.  No smoking."
 'Pet friendly but please confirm with me if the pet you are planning on bringing with you is OK. I have a cute and quiet mixed chihuahua. I could accept more guests (for an extra fee) but this also needs to be confirmed beforehand. Also friends traveling together could sleep in separate beds for an extra fee (the second bed is either a sofa bed or inflatable bed). Smoking is only allowed on the porch.'
 "I encourage you to use my kitchen, cooking and laundry facilities. There is no additional charge to use the washer/dryer in the basement.  No smoking, inside or outside. Come home as late as you want.  If you come home stumbling drunk, it's OK the first time. If you do it again, and you wake up me or the neighbors downstairs, we will be annoyed.  (Just so you know . . . )"
 nan
 'Please no smoking in the house, porch or on the property (you can go to the nearby corner).  Reasonable quiet after 10:30 pm.  Please remove shoes in the house.'
 'No smoking, please, and no drugs.'
 'Please no shoes in the house so bring slippers or extra socks to keep your feet warm- especially in winter! No smoking either inside or outside. Please be considerate of neighbors from 10pm-7am in terms of noise. Please take out any trash and leave in the large blue garbage bin at the end of the driveway when you leave.'
 'House Guidelines for our BnB We are delighted to welcome you.  Check in Sun – Thurs by 8PM and Fri, Sat by 9pm. Please bear in mind that this is not a hotel but our home and we are opening it to you.  We will do our utmost to make your stay enjoyable and fun.  We ask that you take care to respect our home and its appearance.  Thank you.  Marilyn and Alan 1.ROOMS - The bedroom is yours for the duration of your stay.  Be sure to let us know if you need something.  Please keep it neat and tidy and take advantage of the closet and bureau for your belongings.  We do ask that you turn off lights, air conditioner, fan, etc. when you are not in the room. Thank you. 2.LIGHTS – Please, too, remember to turn off lights on the stairway when returning.   3.KEYS - 2 house keys are provided - Replacement cost is $15 each 4.PARKING – Parking is available on street at all times.   5.SHOES – When the weather is inclement please remove shoes.   6.TOILETRIES - If you need them we can provide basic toiletr'
 '- Please clean up after yourself when using the kitchen. - When using the bathroom, please be careful to minimize the amount of water on the floor when showering and using the sink. - Please make sure to remove any strands of hair from the sink and floors with a tissue or paper towel. - Be respectful of the noise levels after 11pm.  - Please be quiet coming in late or leaving early. - No Smoking  - No Pets - No overnight guests - For safety reasons, please make sure to shut and lock the windows and front door when you leave. *** Note: cancellations are subject to fees that are non refundable ***'
 "NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1. Be respectful of the other tenants 2. If you use the grill, be sure to turn off the gas 3. Notify the owner of any discrepancies or things not functioning properly immediately 4. Please treat carpet stains promptly (or notify the owner) 5. Kindly turn off lights, air conditioners, and other electrical items when they aren't needed"]
license : [nan]

In [ ]:
# Dropping specified columns from the DataFrame
airbnb_df.drop(columns=['license','country','country code','last review','house_rules','host_identity_verified','id','NAME','host id','host name'],inplace=True)

In [ ]:
# Checking for missing values in the DataFrame after dropping columns
airbnb_df.isna().sum()

neighbourhood group                  29
neighbourhood                        16
lat                                   8
long                                  8
instant_bookable                    105
cancellation_policy                  76
room type                             0
Construction year                   214
price                               247
service fee                         273
minimum nights                      409
number of reviews                   183
reviews per month                 15879
review rate number                  326
calculated host listings count      319
availability 365                    448
dtype: int64

In [ ]:
# Removing rows with missing values in the 'price' column
airbnb_df=airbnb_df[~airbnb_df['price'].isna()]
airbnb_df.shape

(102352, 16)

In [ ]:
102599-102352

247

In [ ]:
# Checking for missing values again after removing rows with missing 'price'
airbnb_df.isna().sum()

neighbourhood group                  28
neighbourhood                        15
lat                                   8
long                                  8
instant_bookable                    100
cancellation_policy                  71
room type                             0
Construction year                   210
price                                 0
service fee                         239
minimum nights                      409
number of reviews                   183
reviews per month                 15852
review rate number                  326
calculated host listings count      319
availability 365                    448
dtype: int64

In [ ]:
# Removing '$' and ',' characters from 'price' and 'service fee' columns and converting them to float
airbnb_df['price']=airbnb_df['price'].str.replace('$','').str.replace(',','')
airbnb_df['service fee']=airbnb_df['service fee'].str.replace('$','').str.replace(',','')

In [ ]:
# Checking the data types of each column in the DataFrame
airbnb_df.dtypes

neighbourhood group               object
neighbourhood                     object
lat                               object
long                              object
instant_bookable                  object
cancellation_policy               object
room type                         object
Construction year                 object
price                             object
service fee                       object
minimum nights                    object
number of reviews                 object
reviews per month                 object
review rate number                object
calculated host listings count    object
availability 365                  object
dtype: object

In [ ]:
# Filling missing values with a placeholder
airbnb_df=airbnb_df.fillna(value=-999999)

In [ ]:
# Converting selected columns to appropriate data types
airbnb_df[['lat','long','price','service fee','reviews per month']]=airbnb_df[['lat','long','price','service fee','reviews per month']].astype('float')
airbnb_df[['Construction year','minimum nights','number of reviews','review rate number','calculated host listings count','availability 365']]=airbnb_df[['Construction year','minimum nights','number of reviews','review rate number','calculated host listings count','availability 365']].astype('int')

In [ ]:
# Checking the data types of each column in the DataFrame
airbnb_df.dtypes

neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                   int64
price                             float64
service fee                       float64
minimum nights                      int64
number of reviews                   int64
reviews per month                 float64
review rate number                  int64
calculated host listings count      int64
availability 365                    int64
dtype: object

In [ ]:
# Function to generate descriptive statistics for specified columns
def get_descriptive_statistics(df:pd.DataFrame,col_names:list)->pd.DataFrame:
  descp_summary_details:list=[]
  for c_name in ['Construction year','price','service fee','minimum nights','number of reviews','reviews per month','review rate number','calculated host listings count','availability 365']:
    temp_dict=airbnb_df[airbnb_df[c_name]!=-999999][c_name].describe().to_dict()
    temp_dict['Feature Name']=c_name
    descp_summary_details.append(temp_dict)
    del temp_dict
  return pd.DataFrame(descp_summary_details)

In [ ]:
# Generating descriptive statistics for selected columns
descp_summary_df=get_descriptive_statistics(
    df=airbnb_df,
    col_names=['Construction year','price','service fee','minimum nights','number of reviews','reviews per month','review rate number','calculated host listings count','availability 365'],
    )

In [ ]:
descp_summary_df

,count,mean,std,min,25%,50%,75%,max,Feature Name
0,102142.0,2012.487038,5.765066,2003.00,2007.00,2012.00,2017.00,2022.0,Construction year
1,102352.0,625.293536,331.671614,50.00,340.00,624.00,913.00,1200.0,price
2,102113.0,125.038399,66.333513,10.00,68.00,125.00,183.00,240.0,service fee
3,101943.0,8.125619,30.556607,-1223.00,2.00,3.00,5.00,5645.0,minimum nights
4,102169.0,27.487878,49.521341,0.00,1.00,7.00,30.00,1024.0,number of reviews
5,86500.0,1.375068,1.747680,0.01,0.22,0.74,2.01,90.0,reviews per month
6,102026.0,3.279282,1.284458,1.00,2.00,3.00,4.00,5.0,review rate number
7,102033.0,7.927200,32.211222,1.00,1.00,1.00,2.00,332.0,calculated host listings count
8,101904.0,141.119897,135.425491,-10.00,3.00,96.00,269.00,3677.0,availability 365

In [ ]:
del descp_summary_df

In [ ]:
sorted(airbnb_df['availability 365'].unique())

[-999999,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 3677]

In [ ]:
sorted(airbnb_df['minimum nights'].unique())

[-999999,
 -1223,
 -365,
 -200,
 -125,
 -12,
 -10,
 -5,
 -3,
 -2,
 -1,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 39,
 40,
 42,
 43,
 44,
 45,
 47,
 48,
 50,
 53,
 55,
 56,
 57,
 58,
 59,
 60,
 62,
 64,
 65,
 68,
 70,
 74,
 75,
 80,
 81,
 85,
 87,
 88,
 90,
 91,
 93,
 98,
 99,
 100,
 105,
 110,
 114,
 115,
 119,
 120,
 122,
 125,
 128,
 129,
 131,
 133,
 134,
 142,
 144,
 145,
 149,
 150,
 153,
 155,
 160,
 166,
 175,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 189,
 198,
 200,
 210,
 222,
 225,
 240,
 250,
 265,
 268,
 270,
 273,
 275,
 299,
 300,
 307,
 323,
 333,
 340,
 350,
 354,
 360,
 364,
 365,
 366,
 370,
 371,
 398,
 399,
 400,
 452,
 458,
 480,
 500,
 825,
 954,
 999,
 1000,
 1250,
 2645,
 3455,
 5645]

In [ ]:
# Filtering out invalid values in 'minimum nights' and 'availability 365' columns
# Based on Above Analysis we can remove some records
airbnb_df=airbnb_df[airbnb_df['minimum nights']>=0]
airbnb_df=airbnb_df[airbnb_df['availability 365']>=0]
airbnb_df=airbnb_df[airbnb_df['minimum nights']<366]
airbnb_df=airbnb_df[airbnb_df['availability 365']<366]
print(airbnb_df.shape)

(98292, 16)

In [ ]:
102599-98292

4307

In [ ]:
# Generating descriptive statistics again after filtering
descp_summary_df=get_descriptive_statistics(
    df=airbnb_df,
    col_names=['Construction year','price','service fee','minimum nights','number of reviews','reviews per month','review rate number','calculated host listings count','availability 365'],
    )

In [ ]:
descp_summary_df

,count,mean,std,min,25%,50%,75%,max,Feature Name
0,98130.0,2012.489626,5.763392,2003.00,2008.00,2012.00,2017.75,2022.0,Construction year
1,98292.0,625.789851,331.719944,50.00,340.00,626.00,913.00,1200.0,price
2,98062.0,125.141614,66.343466,10.00,68.00,125.00,183.00,240.0,service fee
3,98292.0,7.874507,17.013689,1.00,2.00,3.00,5.00,365.0,minimum nights
4,98166.0,27.154290,48.867710,0.00,1.00,7.00,30.00,1024.0,number of reviews
5,83362.0,1.389219,1.756093,0.01,0.23,0.76,2.03,90.0,reviews per month
6,98008.0,3.287711,1.278845,1.00,2.00,3.00,4.00,5.0,review rate number
7,98002.0,8.048315,32.622870,1.00,1.00,1.00,2.00,332.0,calculated host listings count
8,98292.0,134.458257,129.799474,0.00,2.00,90.00,254.00,365.0,availability 365

In [ ]:
del descp_summary_df

##### Model Training and Summary

In [ ]:
import time
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import mean_squared_error

In [ ]:
def model_run(df:pd.DataFrame,target_columns:list,algos:list,n:int)->pd.DataFrame:
  """
  Train and evaluate models for regression task using specified algorithms.

  Parameters:
      df (pd.DataFrame): The DataFrame containing the dataset.
      target_columns (list): A list of target columns to predict.
      algos (list): A list of tuples, where each tuple contains an algorithm name and an instance of the algorithm.
      n (int): The number of rows to consider from the dataset.
                This can be used to limit and check the time and resource before running large dataset.

  Returns:
      result: A DataFrame containing the feature name, model name, and Mean Squared Error (MSE) for each combination of feature and algorithm.
  """

  # Identifying numeric and categorical features
  numeric_features=df.select_dtypes(include=['float64','int64']).columns
  categorical_features=df.select_dtypes(include=['object']).columns

  # Initializing transformers
  numeric_transformer=StandardScaler()
  categorical_transformer=OneHotEncoder(handle_unknown='ignore')

  # List to store results
  loop_results:list=[]

  print(time.ctime())

  # Iterating over features
  for feature in df.drop(columns=target_columns).columns:

    temp_df=df[[feature]+target_columns]

    # Filtering the dataset based on specified number of rows
    if n>0:
      temp_df=temp_df.head(n)

    # Filtering the dataset based on placeholder value (useful as this takes the true distribution before running the models)
    temp_df=temp_df[temp_df[feature]!=-999999]
    X=temp_df[[feature]]
    Y=temp_df[target_columns]

    # If we have a single Target to predict then models will expect numpy series and not a dataframe
    if len(target_columns):
      Y=Y.squeeze()

    # Preprocessing features
    if feature in numeric_features:
      X=numeric_transformer.fit_transform(X)
    else:
      X=categorical_transformer.fit_transform(X)

    # Splitting data into train and test sets
    X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=123)
    del X,Y

    # Converting to dense array if required
    if not isinstance(X_train,np.ndarray):
      X_train=X_train.toarray()
      X_test=X_test.toarray()

    # Training models and storing results (main loop)
    for algo_name,algo in algos:
      algo.fit(X_train,y_train)
      loop_results.append((
          feature,
          algo_name,
          mean_squared_error(y_test,algo.predict(X_test)),
          ))
      print(algo_name,feature,time.ctime())
      print('='*50)
      del algo_name,algo
  # Model Results
  result_df=pd.DataFrame(loop_results,columns=['Feature','Model','MSE']).sort_values(by=['MSE'],ascending=[True])
  del loop_results
  return result_df

In [ ]:
def display_top_results(df,n,algos)->None:
  """
  Display the top results (features with lowest MSE) for each algorithm.

  Parameters:
      df (pd.DataFrame): The DataFrame containing the model results.
      n (int): The number of top results to display.
      algos (list): A list of tuples, where each tuple contains an algorithm name and an instance of the algorithm.

  Returns:
      None
  """
  for algo_name,algo in algos:
    print('Algorithm Used: ',algo_name)
    print(df[df['Model']==algo_name][['Feature','MSE']].head(n))
    print('='*50)
  del algo_name,algo
  return None

In [ ]:
# Algorithms to run for our Regression Task
custom_algorithms=[
    ('Linear Regression',LinearRegression()),
    ('Decision Tree',DecisionTreeRegressor(random_state=123)),
    ('Naive Bayes',GaussianNB())
]

In [ ]:
# Running the model
model_summary=model_run(df=airbnb_df,target_columns=['price'],algos=custom_algorithms,n=0)
print(model_summary.shape)

Sat Apr 13 10:53:09 2024
Linear Regression neighbourhood group Sat Apr 13 10:53:09 2024
==================================================
Decision Tree neighbourhood group Sat Apr 13 10:53:09 2024
==================================================
Naive Bayes neighbourhood group Sat Apr 13 10:53:13 2024
==================================================
Linear Regression neighbourhood Sat Apr 13 10:53:19 2024
==================================================
Decision Tree neighbourhood Sat Apr 13 10:53:44 2024
==================================================
Naive Bayes neighbourhood Sat Apr 13 10:54:24 2024
==================================================
Linear Regression lat Sat Apr 13 10:54:24 2024
==================================================
Decision Tree lat Sat Apr 13 10:54:25 2024
==================================================
Naive Bayes lat Sat Apr 13 10:54:26 2024
==================================================
Linear Regression long Sat Apr 13 10:54:26 2024
==================================================
Decision Tree long Sat Apr 13 10:54:26 2024
==================================================
Naive Bayes long Sat Apr 13 10:54:27 2024
==================================================
Linear Regression instant_bookable Sat Apr 13 10:54:27 2024
==================================================
Decision Tree instant_bookable Sat Apr 13 10:54:27 2024
==================================================
Naive Bayes instant_bookable Sat Apr 13 10:54:28 2024
==================================================
Linear Regression cancellation_policy Sat Apr 13 10:54:28 2024
==================================================
Decision Tree cancellation_policy Sat Apr 13 10:54:28 2024
==================================================
Naive Bayes cancellation_policy Sat Apr 13 10:54:31 2024
==================================================
Linear Regression room type Sat Apr 13 10:54:31 2024
==================================================
Decision Tree room type Sat Apr 13 10:54:31 2024
==================================================
Naive Bayes room type Sat Apr 13 10:54:35 2024
==================================================
Linear Regression Construction year Sat Apr 13 10:54:35 2024
==================================================
Decision Tree Construction year Sat Apr 13 10:54:35 2024
==================================================
Naive Bayes Construction year Sat Apr 13 10:54:36 2024
==================================================
Linear Regression service fee Sat Apr 13 10:54:36 2024
==================================================
Decision Tree service fee Sat Apr 13 10:54:36 2024
==================================================
Naive Bayes service fee Sat Apr 13 10:54:37 2024
==================================================
Linear Regression minimum nights Sat Apr 13 10:54:37 2024
==================================================
Decision Tree minimum nights Sat Apr 13 10:54:37 2024
==================================================
Naive Bayes minimum nights Sat Apr 13 10:54:38 2024
==================================================
Linear Regression number of reviews Sat Apr 13 10:54:38 2024
==================================================
Decision Tree number of reviews Sat Apr 13 10:54:38 2024
==================================================
Naive Bayes number of reviews Sat Apr 13 10:54:39 2024
==================================================
Linear Regression reviews per month Sat Apr 13 10:54:39 2024
==================================================
Decision Tree reviews per month Sat Apr 13 10:54:39 2024
==================================================
Naive Bayes reviews per month Sat Apr 13 10:54:39 2024
==================================================
Linear Regression review rate number Sat Apr 13 10:54:39 2024
==================================================
Decision Tree review rate number Sat Apr 13 10:54:39 2024
==================================================
Naive Bayes review rate number Sat Apr 13 10:54:40 2024
==================================================
Linear Regression calculated host listings count Sat Apr 13 10:54:40 2024
==================================================
Decision Tree calculated host listings count Sat Apr 13 10:54:40 2024
==================================================
Naive Bayes calculated host listings count Sat Apr 13 10:54:41 2024
==================================================
Linear Regression availability 365 Sat Apr 13 10:54:41 2024
==================================================
Decision Tree availability 365 Sat Apr 13 10:54:41 2024
==================================================
Naive Bayes availability 365 Sat Apr 13 10:54:42 2024
==================================================
(45, 3)

In [ ]:
# Displaying top 10 results
display_top_results(df=model_summary,n=10,algos=custom_algorithms)

Algorithm Used:  Linear Regression
                           Feature            MSE
24                     service fee       1.989963
18                       room type  108746.641971
27                  minimum nights  108749.103541
42                availability 365  108752.798123
36              review rate number  109358.773199
39  calculated host listings count  109438.642012
30               number of reviews  109779.022612
12                instant_bookable  110077.083108
21               Construction year  110166.561876
3                    neighbourhood  110252.340302
==================================================
Algorithm Used:  Decision Tree
                           Feature            MSE
25                     service fee       1.985475
19                       room type  108739.904704
28                  minimum nights  108772.368671
43                availability 365  109137.222445
37              review rate number  109371.429539
40  calculated host listings count  109481.634598
31               number of reviews  110006.253332
13                instant_bookable  110076.544158
22               Construction year  110155.920026
4                    neighbourhood  110252.340302
==================================================
Algorithm Used:  Naive Bayes
                           Feature            MSE
26                     service fee       4.135930
41  calculated host listings count  137752.411816
8                              lat  150644.289159
23               Construction year  174004.302252
35               reviews per month  192343.718347
5                    neighbourhood  192826.124180
17             cancellation_policy  202727.144900
29                  minimum nights  234001.765298
2              neighbourhood group  239735.031899
38              review rate number  261049.455617
==================================================

In [ ]:
# Displaying top 7 results
display_top_results(df=model_summary,n=7,algos=custom_algorithms)

Algorithm Used:  Linear Regression
                           Feature            MSE
24                     service fee       1.989963
18                       room type  108746.641971
27                  minimum nights  108749.103541
42                availability 365  108752.798123
36              review rate number  109358.773199
39  calculated host listings count  109438.642012
30               number of reviews  109779.022612
==================================================
Algorithm Used:  Decision Tree
                           Feature            MSE
25                     service fee       1.985475
19                       room type  108739.904704
28                  minimum nights  108772.368671
43                availability 365  109137.222445
37              review rate number  109371.429539
40  calculated host listings count  109481.634598
31               number of reviews  110006.253332
==================================================
Algorithm Used:  Naive Bayes
                           Feature            MSE
26                     service fee       4.135930
41  calculated host listings count  137752.411816
8                              lat  150644.289159
23               Construction year  174004.302252
35               reviews per month  192343.718347
5                    neighbourhood  192826.124180
17             cancellation_policy  202727.144900
==================================================

In [ ]:
# Displaying top 5 results
display_top_results(df=model_summary,n=5,algos=custom_algorithms)

Algorithm Used:  Linear Regression
               Feature            MSE
24         service fee       1.989963
18           room type  108746.641971
27      minimum nights  108749.103541
42    availability 365  108752.798123
36  review rate number  109358.773199
==================================================
Algorithm Used:  Decision Tree
               Feature            MSE
25         service fee       1.985475
19           room type  108739.904704
28      minimum nights  108772.368671
43    availability 365  109137.222445
37  review rate number  109371.429539
==================================================
Algorithm Used:  Naive Bayes
                           Feature            MSE
26                     service fee       4.135930
41  calculated host listings count  137752.411816
8                              lat  150644.289159
23               Construction year  174004.302252
35               reviews per month  192343.718347
==================================================